### PR TITLE
Google docs workspace addon

### LINKED ISSUE #9: Support Google Sheets
See feedback like:

I've had your addon installed for a while and it's nice to see that it's still maintained in 2022 because now I plan to use it daily.
However I take notes freestyle on Google Sheets, where the addon is not available.
It wouldn't matter to me if row heights became irregular or if equations overflowed, but is it possible to use it in Google Sheets in any way?

### LINKED ISSUE #14: Mobile addon for google docs
Mobile Google docs now supports addons. Make ours compatible.

### PR DESCRIPTION
**Pull request by grimsteel**
Fixes #14
Fixes #9

I basically just remade the Sidebar.html file using the new CardService APIs:
image image

(I just realized I need to add the texrendr/codecogs icons to the bottom)

I just chose some random colors for this:
https://github.com/Divide-By-0/autolatex/blob/8cfb98ed4ee99ba7973867d3003bab35ec4aab2f/Docs/appsscript.json#L26-L29
Let me know what colors you want!

It's probably not a good idea to use Github's "CDN" for the icon. Do you have the icon hosted anywhere else?
https://github.com/Divide-By-0/autolatex/blob/8cfb98ed4ee99ba7973867d3003bab35ec4aab2f/Docs/appsscript.json#L31

I feel like it would be a good idea to redo this confusing status system too:
https://github.com/Divide-By-0/autolatex/blob/8cfb98ed4ee99ba7973867d3003bab35ec4aab2f/Docs/Code.ts#L174-L189

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Hey, colors look fine. Previously, the buttons were aligned so the right edge of the bottom button aligned with the right edge of the derender button. Can you replicate that? Ideally, there would also be more padding around the text inside the button to make it look less crowded.

The Donate button is huge; any chance we could make that like half the size?

Feel free to re-upload that image from github to any other cdn. Imgur maybe?

Agreed on redoing the status system. Enums would be a better choice at the very least.

**Comment by grimsteel** [comment]
> Can you replicate that?

I don't think so. The new Card API doesn't give you that much control over the rendered output. I could try adding spaces, but that might not look the same depending on the device.

> The Donate button is huge; any chance we could make that like half the size?

I might be able to do some aspect ratio hacks

> Feel free to re-upload that image from github to any other cdn. Imgur maybe?

Yes, that works!

**Comment by Divide-By-0** [comment]
Sweet. Those buttons already look better (it's still like a teensy bit off, maybe there's a way to add more blank characters or white periods or spacing or something?)

**Comment by Divide-By-0** [comment]
> The Donate button is huge; any chance we could make that like half the size?
> I might be able to do some aspect ratio hacks

Did this get fixed? @grimsteel

**Pull request merged**
